<?php


namespace app\modules\v1\controllers;
use app\models\KitchenCatalogMain;
use Yii;
use yii\base\Model;

class KitchenCatalogMainController extends ApiController
{
    public $modelClass = 'app\models\KitchenCatalogMain';
    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions;  // TODO: Change the autogenerated stub
    }
    public function actionIndex()
    {
        $categoryId = Yii::$app->request->get('categoryId');
        $models = KitchenCatalogMain::find()
            ->where(['category_id' => $categoryId])
            ->all();
        return $models;
    }

}